### ISSUE TITLE
pyodbc.Error with python module "Can't open lib 'None' : file not found"

### ISSUE THREAD

**Issue by insatomcat** [markhoerth/dremio_client#34]
* Dremio client version: 0.10.1
* Dremio version: 4.1.8
* Python version: 3.8.2
* Operating System: docker/python:3

### Description

Trying to query a dataset using the python module.
The module falls back to ODBC, but then ODBC fails. I'm not quite sure what the prerequisites are to make odbc work (driver ? config ?)

### What I Did

```
root@e5388f7692fa:/work# cat test.py
from dremio_client import init
client = init() # initialise connectivity to Dremio via config file
print(client)
catalog = client.data # fetch catalog
print(catalog)
vds = catalog.DEMO.test.test2.test.get() # fetch a specific dataset
df = vds.query() # query the first 1000 rows of the dataset and return as a DataFrame
print(df)

root@e5388f7692fa:/work# python test.py
<dremio_client.dremio_client.DremioClient object at 0x7f767ba88d60>
{"id": "root"}
WARNING:root:Unable to run query as flight, downgrading to odbc
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    df = vds.query() # query the first 1000 rows of the dataset and return as a DataFrame
  File "/usr/local/lib/python3.8/site-packages/dremio_client/model/data.py", line 747, in query
    return self.sql("select * from {}")
  File "/usr/local/lib/python3.8/site-packages/dremio_client/model/data.py", line 750, in sql
    return self._flight_endpoint(sql)
  File "/usr/local/lib/python3.8/site-packages/dremio_client/dremio_client.py", line 131, in query
    return query(
  File "/usr/local/lib/python3.8/site-packages/dremio_client/query.py", line 64, in query
    return _odbc_query(sql, hostname=hostname, port=odbc_port, username=username, password=password)
  File "/usr/local/lib/python3.8/site-packages/dremio_client/odbc.py", line 89, in query
    client = connect(hostname, port, username, password)
  File "/usr/local/lib/python3.8/site-packages/dremio_client/odbc.py", line 65, in connect
    c = pyodbc.connect(
pyodbc.Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'None' : file not found (0) (SQLDriverConnect)")
```

**Comment by insatomcat** [comment]
I installed the driver in my docker image, linked the /etc/odbcinst.ini to the one proposed in the driver package ... still no luck.
After some debugging I found that the _get_driver_name() is actually never called (https://github.com/rymurr/dremio_client/blob/5efb5c7a08943840da444d34471e0fb6e5583b75/dremio_client/odbc.py#L37) that seems to be the reason why the _DRIVER variable stays "None".

I added a call to this method just before the odbc connection, and now I get : 

```
WARNING:root:Unable to run query as flight, downgrading to odbc
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pandas/io/sql.py", line 1586, in execute
    cur.execute(*args, **kwargs)
pyodbc.Error: ('HY000', '[HY000] [Dremio][Connector] (1040) Dremio failed to execute the query: select * from {}\n[30038]Query execution error. Details:[ \nPARSE ERROR: Failure parsing the query.\n\nSQL Query select * from {}\nstartLine 1\nstartColumn 10\nendLine 1\nendColumn 13\nSQL Query select * from {}\n\n[Error Id: dfab7bc2-1970-4fe2-9f34-9328b5592e5b on mathis-integration.rte-france.com:31010]\n\n  (org.apache.calcite.sql.parser.SqlParseException) Encountered "from {" at...[see log] (1040) (SQLExecDirectW)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 5, in <module>
    df = vds.query() # query the first 1000 rows of the dataset and return as a DataFrame
  File "/usr/local/lib/python3.8/site-packages/dremio_client/model/data.py", line 747, in query
    return self.sql("select * from {}")
  File "/usr/local/lib/python3.8/site-packages/dremio_client/model/data.py", line 750, in sql
    return self._flight_endpoint(sql)
  File "/usr/local/lib/python3.8/site-packages/dremio_client/dremio_client.py", line 131, in query
    return query(
  File "/usr/local/lib/python3.8/site-packages/dremio_client/query.py", line 64, in query
    return _odbc_query(sql, hostname=hostname, port=odbc_port, username=username, password=password)
  File "/usr/local/lib/python3.8/site-packages/dremio_client/odbc.py", line 91, in query
    return pandas.read_sql(sql, client)
  File "/usr/local/lib/python3.8/site-packages/pandas/io/sql.py", line 406, in read_sql
    return pandas_sql.read_query(
  File "/usr/local/lib/python3.8/site-packages/pandas/io/sql.py", line 1633, in read_query
    cursor = self.execute(*args)
  File "/usr/local/lib/python3.8/site-packages/pandas/io/sql.py", line 1598, in execute
    raise ex from exc
pandas.io.sql.DatabaseError: Execution failed on sql 'select * from {}': ('HY000', '[HY000] [Dremio][Connector] (1040) Dremio failed to execute the query: select * from {}\n[30038]Query execution error. Details:[ \nPARSE ERROR: Failure parsing the query.\n\nSQL Query select * from {}\nstartLine 1\nstartColumn 10\nendLine 1\nendColumn 13\nSQL Query select * from {}\n\n[Error Id: dfab7bc2-1970-4fe2-9f34-9328b5592e5b on mathis-integration.rte-france.com:31010]\n\n  (org.apache.calcite.sql.parser.SqlParseException) Encountered "from {" at...[see log] (1040) (SQLExecDirectW)')
```

it seems the query that get sent is : "select * from {}" ...

**Comment by insatomcat** [comment]
see PR #35 for a very dirty fix

**Comment by rymurr** [comment]
thanks a lot @insatomcat will give that PR a check and let you know!
