### ISSUE TITLE
json posted with requests is string, and so is escaped, make all put/post queries fail

### ISSUE THREAD

**Issue by insatomcat** [markhoerth/dremio_client#39]
* Dremio client version: 0.10.1 
* Dremio version: 4.1.8
* Python version: 3.8.2
* Operating System: docker/python:3

### Description

Trying to use the update_catalog endpoint.

### What I Did

```
root@13290d3e7d28:/work# dremio_client update-catalog -i f03366b6-bf34-46dc-b57e-641c1cc46325 '{"entityType": "dataset", "id": "f03366b6-bf34-46dc-b57e-641c1cc46325", "type": "VIRTUAL_DATASET", "path": ["BDF", "example_bug_round"], "sql": "SELECT * FROM bug_round_test limit 1000", "sqlContext": ["@RE00004T"], "accessControlList": {"groups": [{"id": "PrestaBDF", "permissions": ["READ", "WRITE"]}, {"id": "BDF", "permissions": ["READ", "WRITE"]}], "version": "4"}, "fields": [{"name": "ID ", "type": {"name": "DOUBLE"}}, {"name": "value", "type": {"name": "UNION", "subSchema": [{"type": {"name": "DOUBLE"}}, {"type": {"name": "VARCHAR"}}]}}]}'
{"entityType": "dataset", "id": "f03366b6-bf34-46dc-b57e-641c1cc46325", "type": "VIRTUAL_DATASET", "path": ["BDF", "example_bug_round"], "sql": "SELECT * FROM bug_round_test limit 1000", "sqlContext": ["@RE00004T"], "accessControlList": {"groups": [{"id": "PrestaBDF", "permissions": ["READ", "WRITE"]}, {"id": "BDF", "permissions": ["READ", "WRITE"]}], "version": "4"}, "fields": [{"name": "ID ", "type": {"name": "DOUBLE"}}, {"name": "value", "type": {"name": "UNION", "subSchema": [{"type": {"name": "DOUBLE"}}, {"type": {"name": "VARCHAR"}}]}}]}
Traceback (most recent call last):
  File "/usr/local/bin/dremio_client", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/dremio_client/cli.py", line 374, in update_catalog
    x = _update_catalog(token, base_url, cid, data, ssl_verify=verify)
  File "/usr/local/lib/python3.8/site-packages/dremio_client/model/endpoints.py", line 411, in update_catalog
    return _put(base_url + "/api/v3/catalog/{}".format(cid), token, json, ssl_verify=ssl_verify)
  File "/usr/local/lib/python3.8/site-packages/dremio_client/model/endpoints.py", line 60, in _put
    return _check_error(r, details)
  File "/usr/local/lib/python3.8/site-packages/dremio_client/model/endpoints.py", line 72, in _check_error
    raise DremioBadRequestException("Requested object does not exist on entity " + details, error)
dremio_client.error.DremioBadRequestException: Requested object does not exist on entity : 400 Client Error: Bad Request for url: http://XXXX:81/api/v3/catalog/f03366b6-bf34-46dc-b57e-641c1cc46325
```

The problem is that the json is encoded when sent to the server:

```
PUT /api/v3/catalog/f03366b6-bf34-46dc-b57e-641c1cc46325 HTTP/1.1
Host: XXXX:81
User-Agent: python-requests/2.23.0
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Authorization: XXX
content-type: application/json
Content-Length: 641
 
"{\"entityType\": \"dataset\", \"id\": \"f03366b6-bf34-46dc-b57e-641c1cc46325\", \"type\": \"VIRTUAL_DATASET\", \"path\": [\"BDF\", \"example_bug_round\"], \"sql\": \"SELECT * FROM bug_round_test limit 1000\", \"sqlContext\": [\"@RE00004T\"], \"accessControlList\": {\"groups\": [{\"id\": \"PrestaBDF\", \"permissions\": [\"READ\", \"WRITE\"]}, {\"id\": \"BDF\", \"permissions\": [\"READ\", \"WRITE\"]}], \"version\": \"4\"}, \"fields\": [{\"name\": \"ID \", \"type\": {\"name\": \"DOUBLE\"}}, {\"name\": \"value\", \"type\": {\"name\": \"UNION\", \"subSchema\": [{\"type\": {\"name\": \"DOUBLE\"}}, {\"type\": {\"name\": \"VARCHAR\"}}]}}]}"HTTP/1.1 

400 Bad Request
```

**Comment by insatomcat** [comment]
see PR #40
